### ISSUE TITLE
Rename `StringExtensions.format` to `Format` for compliance with C# naming style

### ISSUE THREAD

**Issue by SasLuca** [rmandvikar/csharp-extensions#6]
Seems like a type, but `StringExtensions` has a function called `format` when I am pretty sure it should be `Format` given the C# coding style is for public functions to be in `PascalCase`.

Here is the line in question, hopefully, a quick fix that can be put up on nuget fast:
https://github.com/rmandvikar/csharp-extensions/blob/ee63bb3827af1d567aa6b37ff4c674b868c37f5e/src/rm.Extensions/StringExtension.cs#L104

**Comment by rmandvikar** [comment]
I had went back and forth with the name. I didn't go with `Format()` as it would be confusing due to the `string.Format()`. I thought it won't compile but looks like I'm wrong. I didn't go with `Format2()` as it looks odd. Any suggestions? Note that this will be a breaking change so I'll have to bump the version to `3.x`, and I plan to release that out shortly. 

**Update:**

I think I'm going to go with `Format` like you suggested. I've pushed a fix to the `dev` branch, and cut [`3.0.0-alpha0`](https://github.com/rmandvikar/csharp-extensions/releases/tag/v3.0.0-alpha0).

**Comment by SasLuca** [comment]
What is the reason not to just wrap `String.Format`? Is it because you want parameter indexes to be optional and `String.Format` does not support this?

**Comment by rmandvikar** [comment]
Yes. This is [what I had way back](https://github.com/rmandvikar/csharp-extensions/commit/105b228dce5db01511095aa8dc727e4a97c06cde#diff-42e2dd663385135b57beae40a7d70093aadeb9a68bcb678e75f1d3ae2830f80dR70-R76), which was a simple pass-through. IIRC, this may have [been added](https://github.com/rmandvikar/csharp-extensions/commit/c08952ca5a8a1dc418fa72c7594c16612abda32b) before or around when .Net [came out with interpolated strings](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-60), which somewhat obsoletes this but I let this be as it's not exactly the same.

**Comment by rmandvikar** [comment]
Fixed in [`v3.0.1`](https://github.com/rmandvikar/csharp-extensions/releases/tag/v3.0.1).
